<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Jaydeep" failures="0" tests="1" name="TestNg.ExceptionTimeoutTest" time="0.023" errors="1" timestamp="2022-07-08T17:57:44 EDT" skipped="0">
  <testcase classname="TestNg.ExceptionTimeoutTest" name="InfinitLoopTest" time="0.023">
    <error message="Method TestNg.ExceptionTimeoutTest.InfinitLoopTest() didn&#039;t finish within the time-out 2" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TestNg.ExceptionTimeoutTest.InfinitLoopTest() didn't finish within the time-out 2
at java.base@18.0.1.1/java.io.FileOutputStream.writeBytes(Native Method)
at java.base@18.0.1.1/java.io.FileOutputStream.write(FileOutputStream.java:349)
at java.base@18.0.1.1/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
at java.base@18.0.1.1/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
at java.base@18.0.1.1/java.io.PrintStream.write(PrintStream.java:576)
at java.base@18.0.1.1/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)
at java.base@18.0.1.1/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:313)
at java.base@18.0.1.1/sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:111)
at java.base@18.0.1.1/java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:180)
at java.base@18.0.1.1/java.io.PrintStream.writeln(PrintStream.java:727)
at java.base@18.0.1.1/java.io.PrintStream.println(PrintStream.java:951)
at app//TestNg.ExceptionTimeoutTest.InfinitLoopTest(ExceptionTimeoutTest.java:13)
at java.base@18.0.1.1/java.lang.invoke.LambdaForm$DMH/0x0000000800d12000.invokeVirtual(LambdaForm$DMH)
at java.base@18.0.1.1/java.lang.invoke.LambdaForm$MH/0x0000000800d12800.invoke(LambdaForm$MH)
at java.base@18.0.1.1/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
at java.base@18.0.1.1/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:154)
at java.base@18.0.1.1/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base@18.0.1.1/java.lang.reflect.Method.invoke(Method.java:577)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base@18.0.1.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@18.0.1.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@18.0.1.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@18.0.1.1/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- InfinitLoopTest -->
  <system-out/>
</testsuite> <!-- TestNg.ExceptionTimeoutTest -->
